In [4]:
import numpy as np

np.random.seed(0) #랜덤 seed 지정
np.random.randint(0,1000)

684

In [5]:
np.random.rand(5)

array([0.59284462, 0.84426575, 0.85794562, 0.84725174, 0.6235637 ])

In [7]:
np.random.rand(3,5)

array([[0.29753461, 0.05671298, 0.27265629, 0.47766512, 0.81216873],
       [0.47997717, 0.3927848 , 0.83607876, 0.33739616, 0.64817187],
       [0.36824154, 0.95715516, 0.14035078, 0.87008726, 0.47360805]])

In [10]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
y = np.random.shuffle(x)
y

In [14]:
"""
데이터 샘플링
    - 샘플링(sampling) : 존재하는 데이터 집합에서 일부를 무작위로 선택
    
    - np.random.choice(a,size=None,replace=True,p=None)
        a : 배열, 혹은 정수를 입력할 경우 range(a) 명령으로 데이터 생성
        size : 샘플할 개수 지정
        replace : True 이면 한 번 선택한 데이터를 다시 추출 가능(중복 추출)
        p : a 배열의 데이터들에 대한 선택될 수 있는 확률 지정
"""

x = np.random.choice(10,10,replace=False)
x #셔플 기능과 동일

array([0, 9, 2, 3, 5, 6, 7, 1, 8, 4])

In [16]:
y = np.random.choice(x,5,replace=True)
y #5개 샘플링, 중복 허용

array([5, 5, 7, 5, 5])

In [35]:
np.random.choice(4,3,replace=False,p=[0.9,0.05,0,0.05]) #선택 확률 별도 지정

array([0, 3, 1])

In [38]:
"""
비교 연산 처리
    - 인덱싱 영역에 조건 값을 입력하면 해당 조건에 맞는 데이터 추출 가능
    - 인덱싱 영역에 조건 값을 입력하고 해당 조건에 맞는 영역에 새로운 값을 대입 가능
"""

f=np.random.rand(3,4)
f

array([[0.12381998, 0.84800823, 0.80731896, 0.56910074],
       [0.4071833 , 0.069167  , 0.69742877, 0.45354268],
       [0.7220556 , 0.86638233, 0.97552151, 0.85580334]])

In [40]:
tf = f>0.3
tf

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [44]:
f[f>0.3] = 1