# Numpy 배열 생성 함수와 shape 변환 함수

- 정해진 크기 배열 생성 함수

In [7]:
# zeros 함수는 배열의 모든 원소크기를 0로 지정해준 크기의 배열을 생성합니다,

import numpy as np

A = np.zeros((2,3))
A, A.shape , A.dtype

(array([[0., 0., 0.],
        [0., 0., 0.]]), (2, 3), dtype('float64'))

In [8]:
# ones 함수는 배열의 모든 원소크기를 1로 지정해준 크기의 배열을 생성합니다,

B = np.ones((2,3))
B , B.shape , B.dtype

(array([[1., 1., 1.],
        [1., 1., 1.]]), (2, 3), dtype('float64'))

In [11]:
# empty 함수는 초기화되지 않도록 지정한 크기의 배열을 생성합니다.

C = np.empty((5,5))
C, C.shape, C.dtype

(array([[6.79038653e-313, 2.33419537e-312, 2.44029516e-312,
         1.15928874e-309, 9.70091596e-310],
        [1.02229269e-309, 1.08289689e-309, 1.01397447e-309,
         6.79038882e-313, 1.05140647e-309],
        [9.46240363e-310, 6.79038888e-313, 1.00149713e-309,
         1.09596839e-309, 1.15954338e-309],
        [6.79038907e-313, 9.46240363e-310, 6.79038905e-313,
         1.07534259e-309, 6.79038905e-313],
        [1.04947546e-309, 9.71195034e-310, 9.33678374e-313,
         2.22507386e-306, 4.94065646e-322]]), (5, 5), dtype('float64'))

In [12]:
# random 함수는 0~1 사이의 무작위 값으로 채워진 지정한 크기의 배열을 생성합니다.

D = np.random.random((3,3))
D


array([[0.70856095, 0.94988745, 0.908329  ],
       [0.21771405, 0.31160331, 0.02305907],
       [0.94494885, 0.31156358, 0.51839222]])

In [13]:
# 1~9 사이의 무작위 값을 생성하여 크기 2x2 배열의 원소로 사용

E = np.random.randint(1,10,(5,5))
E

array([[5, 9, 2, 1, 3],
       [1, 3, 4, 3, 8],
       [7, 1, 6, 2, 5],
       [6, 6, 1, 9, 2],
       [9, 3, 9, 1, 4]])