In [4]:
"""
Numpy 기초 사용법
//// 다차원으로 변환
    
    - numpy는 배열은 reshape로 N차원 매트릭스로 변환 가능
    - reshape 명령어 중 원소는 -1로 대체할 수 있다.
        - arr.reshape(4,-1) : 4개 ROW를 가지는 행렬
        - arr.reshape(-1,5) : 5개 COLUMN을 가지는 행렬
"""
import numpy as np


arr = np.array(range(0,20)) #0~19까지 생성
arr_2d = arr.reshape(4,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
arr.reshape(4,-1)
arr.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
arr_1d = arr_3d.flatten()
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
arr_3d = arr.reshape(5, 2, 2)
arr_3d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [16]:
arr_2d.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [17]:
"""
다차원으로의 변환
flatten 메소드 : numpy 다차원 배열을 1차원 리스트로 변환
np.newaxis : 차원을 증가 시킬때 사용
"""
arr_1d = arr_3d.flatten()
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
arr_1d[np.newaxis]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [19]:
arr_1d[np.newaxis,np.newaxis]

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19]]])

In [23]:
"""
배열 붙이기
행(COLUMN)의 수나 열(ROW)의 수가 같은 두개 이상의 배열을 잇는(concatencate) 방법
    -hstack : ROW의 수가 같은 경우, COLUMN으로 붙임 (좌측에서 옆으로)
    -vstack : COLUMN의 수가 같은 경우 ROW로 붙임 (위에서 아래로)
    -stak : 배열을 별개 차원으로 구성한다. (2차원 배열 두 개를 합치면 3차원 배열로)
"""

a1 = np.ones((3,4))
a2 = np.zeros((3,4))

In [28]:
np.hstack([a1,a2])

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [29]:
np.vstack([a1,a2])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.stack([a1,a2])

(2, 3, 4)

In [37]:
"""
집계 함수(aggregate function)

max(배열의 최대 값)
min(배열의 최소 값)
mean(배열의 평균 값)

"""

arr = np.array([[5,6,7,8,9],[0,1,2,3,4]])
arr.max() #9
arr.min() #0
arr.mean() #4.5

arr.max(axis=1) #array([9,4])
arr.min(axis=1) #array([5,0])
arr.mean(axis=1) #array(7.,2.)

arr.max(axis=0) #array([5,6,7,8,9])
arr.min(axis=0) #array([0,1,2,3,4])
arr.mean(axis=0) #array(2.5, 3.5, 4.5, 5.5, 6.5)

array([2.5, 3.5, 4.5, 5.5, 6.5])